apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: jenkinsthx1138
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        BUILDMODE: '--production'
  tagPolicy:
    envTemplate:
      template: '{{.ECR}}/{{.IMAGE_NAME}}:{{.VERSION}}'
  local: {}
deploy:
  helm:
    releases:
    - name: jenkinsthx-prod
      chartPath: charts/jenkinsthx1138
      valuesFiles:
      - charts/jenkinsthx1138/values.yaml
      - charts/jenkinsthx1138/overrides.yaml
      namespace: jenkinsthx
      setValueTemplates:
        image.repository: '{{.ECR}}/jenkinsthx1138'
        image.tag: '{{.VERSION}}'
